### ISSUE TITLE
The distribution has been installed correctly, but when you turn it on, this mistake appears

### ISSUE THREAD

**Issue by ABDO-KAID** [sabamdarif/modded-debian#1]
Hello brother, the distribution has been installed correctly, but there is a problem opening the vnc interface. Please solve the vnc problem

**Comment by ABDO-KAID** [comment]
Hello brother, the distribution has been installed correctly, but there is a problem opening the vnc interface. Please solve the vnc problem

**Comment by sabamdarif** [comment]
> Hello brother, the distribution has been installed correctly, but there is a problem opening the vnc interface. Please solve the vnc problem

Which desktop environment you installed

**Comment by ABDO-KAID** [comment]
Debian desktop environment

**Comment by sabamdarif** [comment]
> Debian desktop environment

No I mean xfce , gnome , kde what ?

**Comment by ABDO-KAID** [comment]
> > Debian desktop environment
> 
> No I mean xfce , gnome , kde what ?

 gnome

**Comment by sabamdarif** [comment]
try the new script .
or try this :- https://github.com/sabamdarif/gnome-in-termux ( my new script which help you to install gnome in termux )
